include:
  - docker-compose.yml

services:

  # vllm service(s)
  vllm-0:
    image: vllm/vllm-openai:latest

  # litellm
  litellm:
    container_name: litellm
    image: ghcr.io/berriai/litellm:main-latest
    command: --config /app/config.yaml
    restart: unless-stopped
    depends_on:
      pgvector:
        condition: service_healthy
    environment:
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY:?error}
      LITELLM_SALT_KEY: ${LITELLM_SALT_KEY:?error}
      DATABASE_URL: postgresql://${LOCAL_DB_POSTGRES_USERNAME?:error}:${LOCAL_DB_POSTGRES_PASSWORD:?error}@pgvector:5432/litellm
    volumes:
      - ./litellm_config.ollama.yml:/app/config.yaml # this should be the litellm config file
    ports:
      - '4000:4000'

networks:
  default:
    name: node-network