# This version of the node dockerfile includes the SurrealDB CLI utilities, and includes initialization for surrealdb
FROM condaforge/miniforge3:24.9.2-0

WORKDIR /app
COPY . .

# use bash instead of sh
SHELL ["/bin/bash", "-c"]


# install deps
RUN apt-get update
RUN apt-get install gcc curl git libpq-dev -y

# add conda install to path; use base environment
ENV PATH="/opt/conda/bin:${PATH}"
RUN conda create -y -n node python=3.12
RUN echo "source activate node" > /root/.bashrc
ENV PATH="/opt/conda/envs/node/bin:$PATH"

# install postgres (required for poetry to build psycopg2 from source)
RUN conda install -y conda-forge::postgresql=17.2
ENV LDFLAGS="-L/opt/conda/lib"
ENV CPPFLAGS="-I/opt/conda/include"

# set up poetry
ENV PATH="/root/.local/share/pypoetry/venv/bin/:${PATH}"
RUN pip install poetry
RUN poetry config virtualenvs.in-project true
RUN poetry lock
RUN poetry install --only main

# install surrealDB so that we have the command line tool
RUN curl -sSf https://install.surrealdb.com | sh

EXPOSE 7001 7002

RUN chmod +x /app/entrypoint.sh
CMD ["/app/entrypoint.sh"]

