# this version of the Node dockerfile does NOT include surrealDB CLI utilities or intialization. See Dockerfile-node-dev
# if you need those capabilities.
FROM condaforge/miniforge3:24.9.2-0

WORKDIR /app
COPY . .

# use bash instead of sh
SHELL ["/bin/bash", "-c"]


# install deps
RUN apt-get update
RUN apt-get install curl gcc curl git -y

# add conda install to path; use base environment
ENV PATH="/opt/conda/bin:${PATH}"
RUN conda create -y -n node python=3.12
RUN echo "source activate node" > /root/.bashrc
ENV PATH="/opt/conda/envs/node/bin:$PATH"
RUN echo

# install postgres (required for poetry to build psycopg2 from source)
RUN conda install -y conda-forge::postgresql=17.2
ENV LDFLAGS="-L/opt/conda/lib"
ENV CPPFLAGS="-I/opt/conda/include"

# set up poetry
ENV PATH="/root/.local/share/pypoetry/venv/bin/:${PATH}"
RUN pip install poetry
RUN poetry config virtualenvs.in-project true
RUN poetry lock
RUN poetry install --only main

EXPOSE 7001 7002

# install surrealDB so that we have the command line tool
RUN curl -sSf https://install.surrealdb.com | sh

# run db migrations / config & server
CMD set -x && \
    poetry run python -m node.storage.db.init_db 2>&1 && \
    poetry run python -m node.storage.hub.init_hub 2>&1 && \
    poetry run python -m node.storage.hub.init_hub --user 2>&1 && \
    ((poetry run celery -A node.worker.main:app worker --loglevel=info | tee /dev/stdout) & ) && \
    ((poetry run python -m node.server.server --communication-protocol http --port 7001) &) && \
    poetry run python -m node.server.server --communication-protocol ws --port 7002
