model_list:

  # vllm-0-hermes
  - model_name: NousResearch/Hermes-3-Llama-3.1-8B
    litellm_params:
      model: openai/NousResearch/Hermes-3-Llama-3.1-8B
      api_base: http://vllm/v1
      api_key: none

general_settings:
  master_key: 'sk-blacklight-key'
