"""Initial migration

Revision ID: 93a8f13057e2
Revises: 
Create Date: 2024-10-16 05:47:16.352725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a8f13057e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_key')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumer_id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('agent_run_params', sa.JSON(), nullable=True),
    sa.Column('results', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('agent_run_type', sa.String(), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('worker_nodes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('child_runs', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('parent_runs', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('start_processing_time', sa.DateTime(), nullable=True),
    sa.Column('completed_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('agent_version', sa.String(), nullable=True),
    sa.Column('agent_source_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['consumer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_runs')
    op.drop_table('users')
    # ### end Alembic commands ###
