name: Build Node Container

on:
  push:
    paths:
      - 'Dockerfile*'
      - '!node/**'
      - '.github/**'
      - 'docker-compose*'
      - 'poetry.lock'
      - 'pyproject.toml'

jobs:
  build-only:
    runs-on: ubuntu-latest
    env:
      HUB_URL: wss://hub.naptha.ai/rpc
      NODE_URL: http://localhost:7001
      NAPTHA_HUB_USERNAME: ${{ secrets.NAPTHA_HUB_USERNAME }}
      NAPTHA_HUB_PVT_KEY: ${{ secrets.NAPTHA_HUB_PVT_KEY }}
      NAPTHA_HUB_PASSWORD: ${{ secrets.NAPTHA_HUB_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Set up env variables
        run: |
          cp .env.example .env
          sed -i 's/^LAUNCH_DOCKER=.*/LAUNCH_DOCKER=true/' .env
          echo "LOCAL_HUB=true" >> .env
          echo "REGISTER_NODE_WITH_HUB=false" >> .env
          echo "OLLAMA_MODELS=" >> .env
          echo "VLLM_MODELS=" >> .env
          echo "OPENAI_MODELS=" >> .env

          echo "Creating PEM file for user: $NAPTHA_HUB_USERNAME"
          PEM_FILE="$NAPTHA_HUB_USERNAME.pem"
          echo "$NAPTHA_HUB_PVT_KEY" > "$PEM_FILE"
          chmod 600 "$PEM_FILE"

          # Replace existing placeholders in .env instead of appending duplicates
          sed -i "s/^PRIVATE_KEY=.*/PRIVATE_KEY=$PEM_FILE/" .env
          sed -i "s/^HUB_USERNAME=.*/HUB_USERNAME=$NAPTHA_HUB_USERNAME/" .env
          sed -i "s/^HUB_PASSWORD=.*/HUB_PASSWORD=$NAPTHA_HUB_PASSWORD/" .env

          sed -i 's|/home/<youruser>/.cache/huggingface|/home/runner/.cache/huggingface|g' .env
          echo "=== .env contents (sanitized) ==="
          grep -v "PASSWORD\|KEY" .env

      - name: Install Naptha SDK
        run: pip install naptha-sdk

      - name: Launch node with Docker
        run: bash launch.sh

      - name: Check Docker containers
        run: |
          sleep 30  # Give containers time to start
          docker ps
          docker compose logs

      - name: Test Naptha SDK
        env:
          HUB_USERNAME: ${{ secrets.NAPTHA_HUB_USERNAME }}
          HUB_PASSWORD: ${{ secrets.NAPTHA_HUB_PASSWORD }}
          NODE_URL: http://localhost:7001
          HUB_URL: ws://localhost:3001/rpc
        run: |
          # Use the generated PEM file from the previous step
          export PRIVATE_KEY="${HUB_USERNAME}.pem"
          echo "Using PRIVATE_KEY file: $PRIVATE_KEY"
          
          echo "Signing up with Naptha..."
          naptha signup
          
          echo "Checking nodes (should show 1 node):"
          naptha nodes
          
          docker stop node-app
          sleep 30
          
          echo "Checking nodes (should be empty):"
          naptha nodes

      - name: Cleanup
        if: always()
        run: |
          ./docker-ctl.sh down || true
          docker system prune -f